export interface Product {
  id: string
  name: string
  description: string
  price: number
  image: string
  category: string
}

export const products: Product[] = [
  {
    id: "1",
    name: 'Букет "Весняна ніжність"',
    description: "Елегантний букет з білих і рожевих троянд з еліксиром свіжості",
    price: 850,
    image: "/elegant-white-and-pink-roses-bouquet.jpg",
    category: "Романтичні",
  },
  {
    id: "2",
    name: 'Композиція "Літній сад"',
    description: "Яскрава композиція з соняшників та хризантем",
    price: 950,
    image: "/bright-sunflowers-and-chrysanthemums-arrangement.jpg",
    category: "Яскраві",
  },
  {
    id: "3",
    name: 'Букет "Червона пристрасть"',
    description: "Класичний букет з червоних троянд премиум класу",
    price: 1200,
    image: "/luxury-red-roses-bouquet.jpg",
    category: "Романтичні",
  },
  {
    id: "4",
    name: 'Композиція "Лавандові мрії"',
    description: "Ніжна композиція з лаванди та евкаліпта",
    price: 780,
    image: "/lavender-and-eucalyptus-flower-arrangement.jpg",
    category: "Ніжні",
  },
  {
    id: "5",
    name: 'Букет "Райський сад"',
    description: "Екзотичний букет з орхідей та антуріумів",
    price: 1450,
    image: "/exotic-orchids-and-anthuriums-bouquet.jpg",
    category: "Екзотичні",
  },
  {
    id: "6",
    name: 'Композиція "Осіння палітра"',
    description: "Тепла композиція з жовтих та оранжевих квітів",
    price: 920,
    image: "/warm-autumn-yellow-orange-flowers.jpg",
    category: "Яскраві",
  },
  {
    id: "7",
    name: 'Букет "Біла елегантність"',
    description: "Витончений букет з білих лілій та фрезій",
    price: 1100,
    image: "/elegant-white-lilies-and-freesias.jpg",
    category: "Елегантні",
  },
  {
    id: "8",
    name: 'Композиція "Рожеві хмари"',
    description: "Повітряна композиція з піоновидних троянд",
    price: 1350,
    image: "/pink-peony-roses-cloud-arrangement.jpg",
    category: "Романтичні",
  },
  {
    id: "9",
    name: 'Букет "Польова свіжість"',
    description: "Натуральний букет з польових квітів",
    price: 650,
    image: "/natural-wildflowers-field-bouquet.jpg",
    category: "Натуральні",
  },
  {
    id: "10",
    name: 'Композиція "Королівський фіолет"',
    description: "Розкішна композиція з фіолетових еустом",
    price: 1050,
    image: "/purple-eustoma-royal-arrangement.jpg",
    category: "Елегантні",
  },
  {
    id: "11",
    name: 'Букет "Тропічний рай"',
    description: "Яскравий букет з екзотичних тропічних квітів",
    price: 1550,
    image: "/bright-tropical-exotic-flowers-bouquet.jpg",
    category: "Екзотичні",
  },
  {
    id: "12",
    name: 'Композиція "Персикова ніжність"',
    description: "М'яка композиція в персикових тонах",
    price: 890,
    image: "/soft-peach-color-flower-arrangement.jpg",
    category: "Ніжні",
  },
  {
    id: "13",
    name: 'Букет "Весняний настрій"',
    description: "Веселий букет з тюльпанів та нарцисів",
    price: 720,
    image: "/spring-tulips-and-daffodils-bouquet.jpg",
    category: "Весняні",
  },
  {
    id: "14",
    name: 'Композиція "Coral Dream"',
    description: "Сучасна композиція в коралових відтінках",
    price: 1180,
    image: "/modern-coral-color-flowers-arrangement.jpg",
    category: "Сучасні",
  },
  {
    id: "15",
    name: 'Букет "Сонячний день"',
    description: "Яскравий букет з жовтих гербер та троянд",
    price: 830,
    image: "/sunny-yellow-gerberas-roses-bouquet.jpg",
    category: "Яскраві",
  },
  {
    id: "16",
    name: 'Композиція "Зимова казка"',
    description: "Святкова композиція з білих та срібних квітів",
    price: 1250,
    image: "/placeholder.svg?height=400&width=400",
    category: "Святкові",
  },
  {
    id: "17",
    name: 'Букет "М\'ятна свіжість"',
    description: "Освіжаючий букет з білих та м'ятних відтінків",
    price: 970,
    image: "/placeholder.svg?height=400&width=400",
    category: "Ніжні",
  },
  {
    id: "18",
    name: 'Композиція "Бордова розкіш"',
    description: "Розкішна композиція з бордових троянд",
    price: 1380,
    image: "/placeholder.svg?height=400&width=400",
    category: "Елегантні",
  },
  {
    id: "19",
    name: 'Букет "Радість життя"',
    description: "Веселий мікс з різнокольорових гербер",
    price: 750,
    image: "/placeholder.svg?height=400&width=400",
    category: "Яскраві",
  },
  {
    id: "20",
    name: 'Композиція "Vintage Romance"',
    description: "Ніжна композиція у вінтажному стилі",
    price: 1420,
    image: "/placeholder.svg?height=400&width=400",
    category: "Романтичні",
  },
]
